### ISSUE TITLE
Add Travis and PyPI autodeploy

### ISSUE THREAD

**Issue by eliasdorneles** [scrapinghub/exporters#288]
The current build is using internal Drone, we should add a Travis build, to run tests and flake like the Drone build is doing.
We should also add support for autodeploy.

It's mostly stealing config from: https://github.com/audreyr/cookiecutter-pypackage/blob/master/.travis.yml and from the `.drone.yml` inside the repo

**Comment by bbotella** [comment]
Only proper user/password for pypi to be set up. Will close after that.

**Comment by bbotella** [comment]
Done with https://github.com/scrapinghub/exporters/pull/299

**Comment by eliasdorneles** [comment]
Did a new patch release after the S3Reader fix, and just confirmed this is working: https://travis-ci.org/scrapinghub/exporters#L1228 =)
https://pypi.python.org/pypi/exporters <- 0.4.14 was deployed from Travis o/
