### ISSUE TITLE
Add a FlatsonTransform to flatten data for CSV output

### ISSUE THREAD

**Issue by eliasdorneles** [scrapinghub/exporters#318]
It would be nice to have a FlatsonTransform that would use [Flatson](http://flatson.readthedocs.io/) to flatten using a given schema in the options.

**Comment by raphapassini** [comment]
@eliasdorneles Please take a look at my patch - https://github.com/scrapinghub/exporters/pull/324

**Comment by eliasdorneles** [comment]
Closed by #324
