### ISSUE TITLE
Add AUTHORS file as mentioned in contributing docs

### ISSUE THREAD

**Issue by eliasdorneles** [scrapinghub/exporters#319]
We're mentioning an `AUTHORS` file in the contributing docs, but it doesn't exists: http://exporters.readthedocs.io/en/latest/contributing.html#coding-style

We could try using https://github.com/pydanny/contributors to generate this file semi-automatically.

**Comment by tsrdatatech** [comment]
Added via https://github.com/scrapinghub/exporters/pull/334
